language: node_js

node_js:
  - 10
  - 8

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        before_script:
          - npm install
          - npm install -g codecov
        script:
          - npm run semantic-release
      after_success:
        - npm run codecov

